### PR TITLE
API and UI updates for managing configs

### PR DESCRIPTION
**Pull request by activeshadow**

### CODE REVIEW

**Comment by activeshadow** [comment]
>     * browser error when going to localhost:3000 (phenix homepage)
>       
>       * screenshot1

Known issue.

>     * create experiment, attempt to click on exp name (not started)
>       
>       * spins, error in browser
>       * screenshot2

I think this was due to an issue with the code in the commit you were testing. Will confirm and fix if the problem still exists.

>     * log table selection not consistent with other tables (e.g. exps)
>       
>       * either have 'edit' button next to 'delete' button (keep all actions as buttons?), or make config name a 'button' similar to the Experiments tab

I'm leaning towards using `edit` and `delete` buttons. @dnkcom what do you prefer?

>     * Configs -> edit some config -> click on Configs tab
>       
>       * no response; should this return user to Configs table?

As the code is written now, no it shouldn't. But we can look into making that the behavior.

>       * if user is in config edit page, and they click a different tab, like Experiements, and then clicks back to Configs, they are presented with the table, rather than the previously editing config page

To make this the behavior (which is a good suggestion), we need to keep track of the config being edited in local storage until it's canceled or saved.

> 
>     * Experiment config -> edit name -> Save
>       
>       * go to experiments tab, name not changed

Will look into this.

>       * attempt to open experiment, fails (exp doesn't exist)

Makes sense given the above.

>       * Not able to select ANY experiment in the experiments tab; tried clicking on a different (unmodified) experiment, and it just hangs in the GUI

Will look into this.

> 
>     * Configs -> create config + -> switch to JSON
>       
>       * ace editor doesn't modify existing text (yaml), so it shows json error
>       * is this supposed to actually change to json?

Yes, should switch to JSON. Should be easy to fix.

>     * Configs -> Edit -> switch to JSON -> click Save
>       
>       * No response, error in browser
>       * screenshot3

Will fix this when we fix the above (the fix for above may end up addressing this).

>     * Configs -> Upload empty yaml
>       
>       * response is "Bad request"...make this more informative? "Malformed YAML"? or something?
>       * Are these being verified against the schemas? If yes, can we show any errors in the file?

In general, we're slowly working on improving error messages back to the user. We will use this as one of our first API endpoints to apply the improved error messages to.

>     * No tooltip on "upload" button

Will add one.

>     * Configs -> Edit -> add garbage in file -> attempt to Save
>       
>       * no response, error in browser
>       * screenshot4

Looking to address this in a few ways... one being client-side schema validation.

>     * Configs -> Edit -> change hostname -> click save
>       
>       * get pop up "this will overwrite....", clicking "Cancel" goes back to config table, rather than continuing to Edit config

Will correct this behavior.

>     * Can start an experiment by clicking the exp name on the Experiments tab -> start, but cannot get to Info tab, exp started OR stopped
>       
>       * may be related to the first error (screenshot1)

I think this was rather related to the 2nd error above. If it's not addressed already we will make sure it is.

>     * CAN WE GET A VIM MODE OPTION FOR ACE?????????

If time permits, we'll add a switch for it!

**Comment by glattercj** [comment]
Looks like all my previous issues were addressed except for one:

- Configs -> Upload empty yaml (or INVALID config; doesn't conform to schema)
  * Response is "Uploading the helloworld.json failed: Bad request"
  * Are these being verified against the schemas? If yes, can we show any errors in the file?
  * This needs to be more informative to let user know what the issue is

**Comment by activeshadow** [comment]
> Looks like all my previous issues were addressed except for one:
> 
>     * Configs -> Upload empty yaml (or INVALID config; doesn't conform to schema)
>       
>       * Response is "Uploading the helloworld.json failed: Bad request"
>       * Are these being verified against the schemas? If yes, can we show any errors in the file?
>       * This needs to be more informative to let user know what the issue is

@glattercj do you mind retesting this particular one again against the latest commit?

**Comment by glattercj** [comment]
> > Looks like all my previous issues were addressed except for one:
> > ```
> > * Configs -> Upload empty yaml (or INVALID config; doesn't conform to schema)
> >   
> >   * Response is "Uploading the helloworld.json failed: Bad request"
> >   * Are these being verified against the schemas? If yes, can we show any errors in the file?
> >   * This needs to be more informative to let user know what the issue is
> > ```
> 
> @glattercj do you mind retesting this particular one again against the latest commit?

I got the schema error pop-up, but only for 2 of the 3 invalid test files :

Should fail:
- `empty.yaml`: schema error pop up (empty file)
- `missing-general`: "...Bad Request" (missing 'general' section, no pop up)
- `invalid.json`: schema error pop up (missing schema header section)

Success:
- `hello-world-topology`: Success (legit topo file)

[upload_test_files.zip](https://github.com/sandia-minimega/phenix/files/7131702/upload_test_files.zip)

**Comment by glattercj** [comment]
- Catch duplicate config and show useful message
- In create config -> have kind-specific templates; i.e. when you change the kind, pre-populate the editor with required fields
- Add export/download config
  * multi-select or individual buttons? ideally would be consistent with other pages (e.g. VMs info tab)

**Comment by activeshadow** [comment]
@glattercj ready for you to test again when you have time!

**Comment by glattercj** [comment]
- multiselect different color than multiselect in VMs info tab
- configs > create new > name=foobar > kind=Experiment > click Create
  * In Experiments tab, new experiment shows up, but has blank name
  * Screen Shot 2021-09-17 at 8 06 07 AM
  * Clicking on blank experiment name takes you to blank page
- configs > upload new config
  * Cannot upload anything other than ".yml"
  * Attempting to upload foo.yaml or bar.json results in "Valid file types are .yaml, .yml, and .json"
- Upload empty .yml
  * "Uploading empty.yml failed: unable to create new config"
  * User needs a better message than this
- Create new experiment from experiments tab with a node that has a network ruleset
  * fails with 404
  * Same error pops up when trying to edit existing experiment config and clicking "Save"
  * In logs for creating new exp:

```txt
phenix      | 2021/09/17 08:19:42 ERROR handlers.go:185: creating experiment baz - validating experiment config: config validation failed: Error at "/topology/nodes/41/network/rulesets/1/rules/0/source": Value is not nullable
phenix      | Schema:
phenix      |   {
phenix      |     "properties": {
phenix      |       "address": {
phenix      |         "example": "10.1.24.60",
phenix      |         "type": "string"
phenix      |       },
phenix      |       "port": {
phenix      |         "example": 3389,
phenix      |         "type": "integer"
phenix      |       }
phenix      |     },
phenix      |     "required": [
phenix      |       "address"
phenix      |     ],
phenix      |     "type": "object"
phenix      |   }
phenix      |
phenix      | Value:
phenix      |   null
```
  * In logs for editing existing config and clicking "Save":

```txt
phenix      | 2021/09/17 08:21:38 INFO error.go:83: {"id":"f6b707e3-f8cc-4430-90e1-bfa5853bc5c0","timestamp":"2021-09-17T08:21:38.234916931-06:00","type":"error","source":"glatter-phenix","message":"config validation failed: Error at \"/topology/nodes/41/network/rulesets/1/rules/0/source\": Value is not nullable","url":"/api/v1/errors/f6b707e3-f8cc-4430-90e1-bfa5853bc5c0","metadata":{"validation":"config validation failed: Error at \"/topology/nodes/41/network/rulesets/1/rules/0/source\": Value is not nullable\nSchema:\n  {\n    \"properties\": {\n      \"address\": {\n        \"example\": \"10.1.24.60\",\n        \"type\": \"string\"\n      },\n      \"port\": {\n        \"example\": 3389,\n        \"type\": \"integer\"\n      }\n    },\n    \"required\": [\n      \"address\"\n    ],\n    \"type\": \"object\"\n  }\n\nValue:\n  null\n"}}
```

**Comment by activeshadow** [comment]
>     * multiselect different color than multiselect in VMs info tab
> 
>     * configs > create new > name=foobar > kind=Experiment > click Create
>       
>       * In Experiments tab, new experiment shows up, but has blank name
>       * Screen Shot 2021-09-17 at 8 06 07 AM
>       * Clicking on blank experiment name takes you to blank page
> 
>     * configs > upload new config
>       
>       * Cannot upload anything other than ".yml"
>       * Attempting to upload foo.yaml or bar.json results in "Valid file types are .yaml, .yml, and .json"
> 
>     * Upload empty .yml
>       
>       * "Uploading empty.yml failed: unable to create new config"
>       * User needs a better message than this
> 
>     * Create new experiment from experiments tab with a node that has a network ruleset
>       
>       * fails with 404
>       * Same error pops up when trying to edit existing experiment config and clicking "Save"
>       * Screen Shot 2021-09-17 at 8 07 52 AM
>       * In logs for creating new exp:
> 
> 
> ```
> phenix      | 2021/09/17 08:19:42 ERROR handlers.go:185: creating experiment baz - validating experiment config: config validation failed: Error at "/topology/nodes/41/network/rulesets/1/rules/0/source": Value is not nullable
> phenix      | Schema:
> phenix      |   {
> phenix      |     "properties": {
> phenix      |       "address": {
> phenix      |         "example": "10.1.24.60",
> phenix      |         "type": "string"
> phenix      |       },
> phenix      |       "port": {
> phenix      |         "example": 3389,
> phenix      |         "type": "integer"
> phenix      |       }
> phenix      |     },
> phenix      |     "required": [
> phenix      |       "address"
> phenix      |     ],
> phenix      |     "type": "object"
> phenix      |   }
> phenix      |
> phenix      | Value:
> phenix      |   null
> ```
> 
>     * In logs for editing existing config and clicking "Save":
> 
> 
> ```
> phenix      | 2021/09/17 08:21:38 INFO error.go:83: {"id":"f6b707e3-f8cc-4430-90e1-bfa5853bc5c0","timestamp":"2021-09-17T08:21:38.234916931-06:00","type":"error","source":"glatter-phenix","message":"config validation failed: Error at \"/topology/nodes/41/network/rulesets/1/rules/0/source\": Value is not nullable","url":"/api/v1/errors/f6b707e3-f8cc-4430-90e1-bfa5853bc5c0","metadata":{"validation":"config validation failed: Error at \"/topology/nodes/41/network/rulesets/1/rules/0/source\": Value is not nullable\nSchema:\n  {\n    \"properties\": {\n      \"address\": {\n        \"example\": \"10.1.24.60\",\n        \"type\": \"string\"\n      },\n      \"port\": {\n        \"example\": 3389,\n        \"type\": \"integer\"\n      }\n    },\n    \"required\": [\n      \"address\"\n    ],\n    \"type\": \"object\"\n  }\n\nValue:\n  null\n"}}
> ```

@glattercj these have all been addressed in the latest commits. Please test again when you can. Thanks!

**Comment by glattercj** [comment]
LGTM

**Pull request merged**
