### PR TITLE
Added functions to start/stop packet captures via subnet

### PR DESCRIPTION
**Pull request by eric-c-wood**
This PR applies to #44.  Functions were added to both the Web UI and command line to enable starting/stopping packet captures via an ipv4 subnet.  

**Current Known Limitations:** Since the minimega capture cli does not currently allow packet captures to be stopped for a specific VM interface, when stopping packet captures for a subnet, all packet captures are stopped for all VMs with an interface in the specified subnet.  This is not the ideal behavior.  An issue has been submitted to the minimega respository https://github.com/sandia-minimega/minimega/issues/1447

**Web UI Examples**
Using the recently merged PR #41 (extended Web UI search), the search bar can be used to specify an ipv4 subnet.  When a valid ipv4 subnet is entered, the `play` button adjacent to the IPv4 label will be enabled.
capture_start_enable

Once there are valid captures, the `stop` button adjacent to the `play` button will be enabled.
show_capture_stop_button

To stop all packet captures for all subnets, the term `capturing` can be entered in the search bar.
stop_all_subnets

There were also command line equivalents added.  An optional filter can be specified on the command line that has the same syntax/keywords as the search terms entered in the Web UI search bar.

### CODE REVIEW

**Comment by activeshadow** [comment]
@eric-c-wood there's been lots of changes since you created this PR. My apologies for not getting to it sooner. I'll try to test it ASAP rebased on the current main branch. More to come.

**Comment by activeshadow** [comment]
@eric-c-wood @glattercj I rebased this branch onto the latest `main` commit and force pushed it back to Eric's fork. I had to fix a few merge conflicts along the way, so I would appreciate it if one or both of you could test it one last time before I merge it in.

**Comment by glattercj** [comment]
LGTM. Can we make sure this documented in [phenix-docs](https://github.com/sandia-minimega/phenix-docs), especially the special terms for the input box? Don't want this to get lost :)

**Review by glattercj — APPROVED** [review]
LGTM. Please make sure this is documented in phenix-docs, especially the options for the input box.

**Comment by activeshadow** [comment]
@eric-c-wood can you submit a PR for documenting this in phenix-docs?

**Comment by eric-c-wood** [comment]
@activeshadow @glattercj With regards to the phenix-docs PR, I am debating whether I should document this feature in the vms.md or create a new md that applies more to the GUI and applying actions to multiple VMs at once.  After all, we never really documented all the additional buttons that were added or the extended search feature that was added.  I might end up updating both vms.md and create a new md for applying actions to multiple vms.  Anyway, I will try to get this documentation completed by the end of this week.  Let me know what you think.

**Comment by glattercj** [comment]
> @activeshadow @glattercj With regards to the phenix-docs PR, I am debating whether I should document this feature in the vms.md or create a new md that applies more to the GUI and applying actions to multiple VMs at once. After all, we never really documented all the additional buttons that were added or the extended search feature that was added. I might end up updating both vms.md and create a new md for applying actions to multiple vms. Anyway, I will try to get this documentation completed by the end of this week. Let me know what you think.

More documentation is ALWAYS better :) I like the idea of updating the existing vms and also adding a new actions for vms/multiple vms page.

**Comment by activeshadow** [comment]
> > @activeshadow @glattercj With regards to the phenix-docs PR, I am debating whether I should document this feature in the vms.md or create a new md that applies more to the GUI and applying actions to multiple VMs at once. After all, we never really documented all the additional buttons that were added or the extended search feature that was added. I might end up updating both vms.md and create a new md for applying actions to multiple vms. Anyway, I will try to get this documentation completed by the end of this week. Let me know what you think.
> 
> More documentation is ALWAYS better :) I like the idea of updating the existing vms and also adding a new actions for vms/multiple vms page.

@eric-c-wood @glattercj I agree with both of you. Sounds like a plan.

**Pull request merged**
