### PR TITLE
Migrate minibuilder from minimega into phenix

### PR DESCRIPTION
**Pull request by activeshadow**
* Migrate minimega minibuilder into phenix UI
* Refactor builder to save topologies directly to phenix store
* Allow for creation of experiment from builder topology if a scenario is selected
* Maintain ability to edit topology nodes and VLANs

### CODE REVIEW

**Comment by activeshadow** [comment]
@aherna please review this PR at your earliest convenience.

**Comment by activeshadow** [comment]
@aherna this is ready for another review when you have time.

**Review by aherna — DISMISSED** [review]
LGTM and tested. except scenario issue.

**Comment by glattercj** [comment]
Can you open an existing topology in Builder? Or just create -> Add?

**Comment by aherna** [comment]
Just create/add atm. I have a new request out to include some of those features. I can give you a tour of current build Monday.

**Comment by activeshadow** [comment]
@aherna any idea when you'll be able to test the latest push? Should fix the experiment creation issue you were having. I'd like to get this merged in ASAP...

**Comment by aherna** [comment]
LGTM @activeshadow  Fixes the issue with scenarios

**Pull request merged**
