### PR TITLE
VM disk referenced in topology is displayed

### PR DESCRIPTION
**Pull request by eric-c-wood**
Addresses issue #49

### CODE REVIEW

**Comment by glattercj** [comment]
@eric-c-wood Yes; let's do relative paths from the minimega files directory.

**Comment by activeshadow** [comment]
> @eric-c-wood Yes; let's do relative paths from the minimega files directory.

What if the image isn't in the minimega files directory? From @glattercj's original comment, I take the idea to be showing a relative path if the image is in the minimega files directory, and a full path if it's not. Is that correct?

Personally, I lean towards showing the full path all the time, but that does make the dropdown inputs bigger. If we show relative paths for some and full paths for others, will that confuse the users?

**Comment by glattercj** [comment]
> > @eric-c-wood Yes; let's do relative paths from the minimega files directory.
> 
> What if the image isn't in the minimega files directory? From @glattercj's original comment, I take the idea to be showing a relative path if the image is in the minimega files directory, and a full path if it's not. Is that correct?
> 
> Personally, I lean towards showing the full path all the time, but that does make the dropdown inputs bigger. If we show relative paths for some and full paths for others, will that confuse the users?

Good point. How about showing the full filename only (including any extension) in the dropdown, and having the full path shown as the tooltip?

**Comment by eric-c-wood** [comment]
@glattercj @activeshadow I have made the following changes based on your comments/suggestions:

1. Images in the Stopped Experiment View are populated from image names defined in the experiment topology and image files found in directories relative to the minimega files directory.  When searching subdirectories relative to the minimega files directory, experiment directories are excluded except for the listed experiment. (e.g. disk snapshots found in experiment directories will only be included for the listed experiment)
2. A tooltip is used to show the full file path and the value in the Disk dropdown listbox is the base file name.  Duplicate base file names will not be shown.  Consequently, if there is a file called vyatta.qcow2 located in /phenix/images and in /tmp, only the first location will be listed.  Preference is given for files found relative to the minimega files directory.  
3. Added the ".hdd" extension when listing files relative to the minimega files directory.  Image names listed in the experiment topology can have any extension.  What is the consequence for allowing other extensions besides qc2 and qcow2?  Are there other sections of code that rely on specific file extensions for image names?

**Comment by glattercj** [comment]
@eric-c-wood Can you fix these conflicts? I think it should be ready after that.

**Comment by eric-c-wood** [comment]
@glattercj Merge conflicts should now be resolved.

**Comment by activeshadow** [comment]
@eric-c-wood so sorry for the delay on this! I'll get the merge conflict addressed and get this merged in.

**Comment by activeshadow** [comment]
@eric-c-wood as usual, I need to find time to test and merge this in. Will try to do so ASAP. Thanks again for your patience!

**Comment by activeshadow** [comment]
@eric-c-wood @glattercj similar to Eric's other PR, I rebased this branch onto the latest main commit and force pushed it back to Eric's fork. I had to fix a lot of merge conflicts along the way, so I would appreciate it if one or both of you could test it one last time before I merge it in.

**Comment by glattercj** [comment]
@activeshadow Getting a panic when starting up the phenix container:

```log
phenix      | panic: concurrent write to websocket connection
phenix      |
phenix      | goroutine 107 [running]:
phenix      | github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc0006ddf80, 0x1, {0x0, 0x4133a5, 0xc0001dabc0})
phenix      |   github.com/gorilla/websocket@v1.4.2/conn.go:610 +0x52b
phenix      | github.com/gorilla/websocket.(*messageWriter).Close(0x1e)
phenix      |   github.com/gorilla/websocket@v1.4.2/conn.go:724 +0x45
phenix      | github.com/gorilla/websocket.(*Conn).beginMessage(0xc00014c580, 0xc0001dabf8, 0x8)
phenix      |   github.com/gorilla/websocket@v1.4.2/conn.go:473 +0x42
phenix      | github.com/gorilla/websocket.(*Conn).WriteMessage(0xc00014c580, 0xffffffffffffffff, {0x1df9d68, 0x0, 0xc0001dacd8})
phenix      |   github.com/gorilla/websocket@v1.4.2/conn.go:757 +0x8b
phenix      | phenix/web/broker.(*Client).stop(0xc0003aa070)
phenix      |   phenix/web/broker/client.go:88 +0x65
phenix      | sync.(*Once).doSlow(0xe4f440, 0xc0001dad88)
phenix      |   sync/once.go:68 +0xd2
phenix      | sync.(*Once).Do(...)
phenix      |   sync/once.go:59
phenix      | phenix/web/broker.(*Client).Stop(...)
phenix      |   phenix/web/broker/client.go:81
phenix      | phenix/web/broker.Start()
phenix      |   phenix/web/broker/broker.go:67 +0x73c
phenix      | created by phenix/web.Start
phenix      |   phenix/web/server.go:163 +0x20bb
```

**Comment by glattercj** [comment]
I'm not seeing any disk info now...

Screen Shot 2022-01-08 at 3 27 54 PM

**Review by glattercj — APPROVED** [review]
LGTM

**Pull request merged**
