### PR TITLE
Support delaying the start of VMs

### PR DESCRIPTION
**Pull request by activeshadow**
Add a `delay` key to the topology node configuration that supports delaying the start of a VM based on a timer, the cc client of another VM, or manual user intervention.

The new top-level topology node option `delay` is now supported. This option has the following schema.
    
 ```
 delay:
   user: bool
   timer: duration string (e.g., 5m)
   c2: string array
 ```

### CODE REVIEW

**Comment by activeshadow** [comment]
@aherna please test this branch at your earliest convenience. Below is an experiment you can use to test with if you like.
```
apiVersion: phenix.sandia.gov/v1
kind: Experiment
metadata:
  name: delay
spec:
  topology:
    nodes:
    - delay:
        c2:
        - VM2
      general:
        hostname: VM1
      hardware:
        cpu: Broadwell
        drives:
        - image: miniccc.qc2
        memory: 512
        os_type: linux
        vcpus: 1
      network:
        interfaces:
        - address: 10.0.0.11
          mask: 24
          name: IF0
          proto: static
          type: ethernet
          vlan: LAN
      type: VirtualMachine
    - delay:
        user: true
      general:
        hostname: VM2
      hardware:
        cpu: Broadwell
        drives:
        - image: miniccc.qc2
        memory: 512
        os_type: linux
        vcpus: 1
      network:
        interfaces:
        - address: 10.0.0.12
          mask: 24
          name: IF0
          proto: static
          type: ethernet
          vlan: LAN
      type: VirtualMachine
    - delay:
        timer: 2m
      general:
        hostname: VM3
      hardware:
        cpu: Broadwell
        drives:
        - image: miniccc.qc2
        memory: 512
        os_type: linux
        vcpus: 1
      network:
        interfaces:
        - address: 10.0.0.13
          mask: 24
          name: IF0
          proto: static
          type: ethernet
          vlan: LAN
      type: VirtualMachine
    - delay:
        c2:
        - VM3
      general:
        hostname: VM4
      hardware:
        cpu: Broadwell
        drives:
        - image: miniccc.qc2
        memory: 512
        os_type: linux
        vcpus: 1
      network:
        interfaces:
        - address: 10.0.0.14
          mask: 24
          name: IF0
          proto: static
          type: ethernet
          vlan: LAN
      type: VirtualMachine
```
With the above experiment configuration, the following should happen:
* VM2 will not start until a user manually starts it (e.g., with `minimega -e vm start VM2`).
* VM1 will start once the cc client for VM2 is active.
* VM3 will start after 2 minutes.
* VM4 will start once the cc client for VM3 is active.

**Comment by aherna** [comment]
They Will Show up in info view, at the moment will need to start via mini cli or miniweb, probably worth having an indicator on the phenix UI.

**Comment by aherna** [comment]
Example a phenix app launches the VM when ready

**Comment by activeshadow** [comment]
> They Will Show up in info view, at the moment will need to start via mini cli or miniweb, probably worth having an indicator on the phenix UI.

You could always start a user delayed VM using the phenix UI. The UI now also indicates VMs that are not started because they were delayed (including what type of delay).

**Pull request merged**
