### PR TITLE
Add support for secure UI

### PR DESCRIPTION
**Pull request by activeshadow**
Use the `--tls-key` and `--tls-cert` options now present for the `phenix ui` subcommand to secure the UI with the provided TLS certificate.

### CODE REVIEW

**Comment by activeshadow** [comment]
@aherna test out this PR when you get a chance. This is in response to your request for TLS support.

**Comment by aherna** [comment]
> @aherna test out this PR when you get a chance. This is in response to your request for TLS support.

@activeshadow there are merge conflicts with the builder branch

**Comment by activeshadow** [comment]
> > @aherna test out this PR when you get a chance. This is in response to your request for TLS support.
> 
> @activeshadow there are merge conflicts with the builder branch

@aherna yeah I don't worry about merge conflicts between development/bug/feature branches.

**Comment by aherna** [comment]
LGTM

**Review by aherna — APPROVED** [review]
LGTM

**Pull request merged**
