### PR TITLE
Added backend paging/sorting to stopped experiment view

### PR DESCRIPTION
**Pull request by eric-c-wood**
Updated the StoppedExperiment.vue to be enable the backend sorting/paging that already exists in the RunningExperiment.vue.  It looks like the intent at one point was to enable backend sorting/paging for the stopped experiment view as there was already code setup to handle backend paging/sorting for the stopped experiment view. See  https://github.com/sandia-minimega/phenix/blob/main/src/go/web/handlers.go#L231

### CODE REVIEW

**Comment by glattercj** [comment]
@eric-c-wood I can page/sort on the stopped experiment view from the code in `main` branch -- can you explain more what this is addressing?

**Comment by eric-c-wood** [comment]
@glattercj I noticed that the running experiment view relied on the server for paging/sorting and was wondering if it was desired to have the stopped experiment view also rely on the server for paging/sorting versus relying on Javascript in the browser client.  It looked like there was at one point the intent to rely on the server for paging/sorting for the stopped experiment view.  

https://github.com/sandia-minimega/phenix/blob/622285649542923982cb7419eb4695462db46eb6/src/go/web/handlers.go#L221-L234

https://github.com/sandia-minimega/phenix/blob/622285649542923982cb7419eb4695462db46eb6/src/go/web/handlers.go#L299-L308

As you mentioned, the browser client paging/sorting works perfectly.  If the intent is to rely on the server for paging/sorting for the running experiment view but rely on the browser for paging/sorting for the stopped experiment view, then we should close this PR.

**Comment by glattercj** [comment]
@activeshadow I'll let you decide this one.

**Comment by activeshadow** [comment]
@glattercj I'm fine with moving paging/sorting for stopped experiments to the server.

@eric-c-wood can you confirm paging/sorting works as it previously did for stopped experiments now that you've moved it server-side (I haven't had a chance to test this PR)? If so I'm fine with merging.

**Comment by eric-c-wood** [comment]
@activeshadow While testing, paging did not work as expected.  I added another commit to fix the paging.  Sorting worked as expected.

**Comment by glattercj** [comment]
@eric-c-wood Once you fix the conflicts this is ready to merge.

**Comment by eric-c-wood** [comment]
@glattercj conflicts should now be resolved.

**Pull request merged**
